### ISSUE TITLE
C:\Users\铁皮\.transparent-background does not exist.

### ISSUE THREAD

**Issue by secrectFG** [john-mnz/ComfyUI-Inspyrenet-Rembg#22]
Windows10
python 3.10

这段代码看起来好像是不支持中文路径，特别是我不是故意使用中文路径，而是user正好是中文
This code seems to not support Chinese paths, especially since I didn't use Chinese paths intentionally, but the user happened to be Chinese.

Traceback (most recent call last):
  File "E:\AIWorkspace\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\AIWorkspace\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\AIWorkspace\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\AIWorkspace\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\AIWorkspace\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Inspyrenet-Rembg\Inspyrenet_Rembg.py", line 69, in remove_background
    remover = Remover(jit=True)
  File "E:\AIWorkspace\ComfyUI-aki-v1.3\python\lib\site-packages\transparent_background\Remover.py", line 120, in __init__
    torch.jit.save(self.model, os.path.join(ckpt_dir, ckpt_name))
  File "E:\AIWorkspace\ComfyUI-aki-v1.3\python\lib\site-packages\torch\jit\_serialization.py", line 83, in save
    m.save(f, _extra_files=_extra_files)
  File "E:\AIWorkspace\ComfyUI-aki-v1.3\python\lib\site-packages\torch\jit\_script.py", line 753, in save
    return self._c.save(str(f), **kwargs)
RuntimeError: Parent directory C:\Users\铁皮\.transparent-background does not exist.

**Comment by mariusfranzen** [comment]
I have the same issue, but my name has this character in it: "é"

**Comment by 2162641485** [comment]
I also encountered this problem, did you solve it?

**Comment by set-soft** [comment]
You can workaround it using defining the TRANSPARENT_BACKGROUND_FILE_PATH environment variable to point to some path without the issue.
